print ("\t\t\t\t\b\b\b\b  I \n")
print ("\t\t\t\t\b\b\b\b\b Think \n")
print ("\t\t\t That I shall \n")
print ("\t\t\t\b\b Never see a poem \n")
print ("\t\t\t\b\b\b\b As lovely as a tree, \n")
print ("\t\t\t\b\b\b\b\b\b\b A tree whose hungry mouth \n")
print ("\t\t\b Is pressed against the earth’s \n")
print ("\t\t\b\b\b Sweet flowing breast, a tree that \n")
print ("\t\t\b\b\b\b Looks at God all day, and lifts it’s \n")
print ("\t\t\b\b\b\b\b\b  Leafy arms to pray. A tree that may in \n")
print ("\t\t\b\b\b\b\b\b Summer wear, a nest of robin in her hair; \n")
print ("\t Upon whose bosom snow has lain; who intimately \n")
print ("\t\t\t\b Lives with rain. \n")
print ("\t\t\t\t\b\b\b\b\b\b\b\b\b\b Poems are made by \n")
print ("\t\t\t Fools like Me \n")
print ("\t\t\t\t\b\b\b But \n")
print ("\t\t\t\t\b\b\b Only \n")
print ("\t\t\t\t\b\b\b God \n")
print ("\t\t\t\t\b\b\b Can \n")
print ("\t\t\t\t\b\b\b Make \n")
print ("\t\t\t\t\b\b A \n")
print ("\t\t\t\t\b\b\b Tree \n")
print ("\t\t\t\t\b\b\b\b\b\b\b JOYCE KILMER \n")